/* GENERATED by scripts/photos.mjs — do not edit by hand.
   Re-runs automatically on `npm run dev` and `npm run build`. */

export interface PhotoFile {
  slot: number;
  src: string;
  width: number;
  height: number;
  blurDataURL: string;
}

export const photoFiles: PhotoFile[] = [
  {
    "slot": 1,
    "src": "/images/photo-1.jpeg",
    "width": 560,
    "height": 1214,
    "blurDataURL": "data:image/webp;base64,UklGRqQAAABXRUJQVlA4IJgAAAAwBgCdASoUACsAPt1go0yopaMiMBVdURAbiUAX5wXPFj4baONfUWBVATJz9v3mO8NII9NF/Bg6AlLAAP7vR5x6xrgqYuNPD0Nmofo25B9PDJybNCAwis5XeaXbqu+g5dI9ceDhkRbBv6IpGreFD+1lDLLtfNyzsjLHgi/NJmYZImNm8LdvEJOEKWNEg+j8IAzAlrwldMAAAA=="
  },
  {
    "slot": 2,
    "src": "/images/photo-2.jpeg",
    "width": 590,
    "height": 1280,
    "blurDataURL": "data:image/webp;base64,UklGRrAAAABXRUJQVlA4IKQAAAAQBgCdASoUACwAPt1gqE6opaOiKrgMARAbiUmACmgB3VOzxp/GE4D4eaMT56Qzv8JyxtTz5X0dcOgA/ukdDkr5TCm3sUtZXbzAAPueT0Ptv8qHkg68U+bYj4rBF4Byqo94a6iJ01vzleWBoPIF8inEz+xFZPFdUA/EMK9t6+CZ3UZbR17wF3ViivcYUWsjhU4OBgw2v3rV0yJzX1AGmKQUbl5gAA=="
  },
  {
    "slot": 3,
    "src": "/images/photo-3.jpeg",
    "width": 591,
    "height": 1280,
    "blurDataURL": "data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAABwBgCdASoUACwAPtFWoUyoJKMltVgMAQAaCWcAvVgVYlcJzJBNCYO1HRrKR9t047g4xnpKj+pve1BxkAAA/uRGoYKVv97BvQ9pvQTsVUdqtXojlCCzd4XbqLObZLpJT6sPAtUUj4gIHr3DQr8+VwZ1aYb7G6IsQjMynsDlW2LojkM56GJHQyLxO1ydJctcQAA="
  },
  {
    "slot": 4,
    "src": "/images/photo-4.jpeg",
    "width": 591,
    "height": 1280,
    "blurDataURL": "data:image/webp;base64,UklGRr4AAABXRUJQVlA4ILIAAACQBgCdASoUACwAPsFOnkynpCMiOrzIAPAYCWQAuzNZABxnf45J92fj0kG4cTBpx/di6zToWYtvO8EPwW5IAP7pUTL7635lC6l0NSoFDZ8ehO9cGZiVQLfrf7aMWXTu2/+maCrGZSEYYpnEklDFND0r64pBpBi/ySM5XdVocByB9uqAqZZPuMFsYlujhXwe30KyntJjqnd7VrIdCR6OzuPHiKm6HXHhIs67SsgtHSlZkAAA"
  }
];

export const photoFile = (slot: number): PhotoFile | undefined =>
  photoFiles.find((p) => p.slot === slot);
