/**
 * Reads every photograph in public/images and writes data/photos.generated.ts.
 *
 * Why this exists: the frames need each photo's real pixel dimensions so the
 * browser reserves exactly the right space (no layout shift as they load), and
 * a tiny blurred version so a frame fills with the photo's own colour while the
 * full file arrives instead of sitting as an empty box.
 *
 * Runs automatically before `npm run dev` and `npm run build`, so dropping a new
 * file into public/images is the only step. Missing files are not an error —
 * the site is designed to look finished without them.
 */

import { readdir, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import sharp from 'sharp';

const IMAGES_DIR = path.join(process.cwd(), 'public', 'images');
const OUT_FILE = path.join(process.cwd(), 'data', 'photos.generated.ts');
const EXT = /\.(jpe?g|png|webp|avif)$/i;

/** photo-1.jpeg → 1, so the slot is the filename and never the sort order. */
const slotOf = (name) => {
  const m = name.match(/photo-(\d+)\./i);
  return m ? Number(m[1]) : null;
};

async function main() {
  let files = [];
  if (existsSync(IMAGES_DIR)) {
    files = (await readdir(IMAGES_DIR))
      .filter((f) => EXT.test(f))
      .filter((f) => slotOf(f) !== null)
      .sort((a, b) => slotOf(a) - slotOf(b));
  }

  const entries = [];
  for (const file of files) {
    const abs = path.join(IMAGES_DIR, file);
    try {
      const img = sharp(abs).rotate(); // honour EXIF orientation
      const meta = await img.metadata();
      if (!meta.width || !meta.height) continue;

      // A 20px-wide version, inlined. Big enough to read as the photo's
      // colour and shape, small enough to cost nothing.
      const blur = await img
        .clone()
        .resize(20, null, { fit: 'inside' })
        .blur(1.1)
        .webp({ quality: 45 })
        .toBuffer();

      entries.push({
        slot: slotOf(file),
        src: `/images/${file}`,
        width: meta.width,
        height: meta.height,
        blurDataURL: `data:image/webp;base64,${blur.toString('base64')}`,
      });
    } catch (err) {
      console.warn(`[photos] skipped ${file}: ${err.message}`);
    }
  }

  const body = `/* GENERATED by scripts/photos.mjs — do not edit by hand.
   Re-runs automatically on \`npm run dev\` and \`npm run build\`. */

export interface PhotoFile {
  slot: number;
  src: string;
  width: number;
  height: number;
  blurDataURL: string;
}

export const photoFiles: PhotoFile[] = ${JSON.stringify(entries, null, 2)};

export const photoFile = (slot: number): PhotoFile | undefined =>
  photoFiles.find((p) => p.slot === slot);
`;

  await writeFile(OUT_FILE, body, 'utf8');

  if (!entries.length) {
    console.log('[photos] none found — frames will show their placeholders.');
  } else {
    console.log(
      `[photos] ${entries.length} found: ` +
        entries.map((e) => `#${e.slot} ${e.width}x${e.height}`).join(', '),
    );
  }
}

main().catch((err) => {
  // Never block a build over artwork.
  console.warn('[photos] skipped:', err.message);
});
